export interface Locality {
  name: string;
  salidas: string;
  entrega: string;
}

const S = "Lunes, miércoles y viernes";
const E = "Hasta 96hs hábiles";

export const COVERED_PROVINCES = new Set([
  "San Juan", "Mendoza", "San Luis", "Catamarca", "La Rioja",
  "Santiago del Estero", "Tucumán", "Salta", "Jujuy", "Santa Fe",
  "Chaco", "Formosa", "Corrientes", "Misiones", "Buenos Aires",
  "Ciudad de Buenos Aires", "La Pampa", "Neuquén", "Río Negro", "Córdoba",
  "Tierra del Fuego", "Chubut", "Entre Ríos", "Santa Cruz",
]);

export const PROVINCE_LOCALITIES: Record<string, Locality[]> = {
  "Catamarca": [
    { name: "Andalgalá", salidas: S, entrega: E },
    { name: "Antofagasta de la Sierra", salidas: S, entrega: E },
    { name: "Belén", salidas: S, entrega: E },
    { name: "Colonia Nueva Coneta", salidas: S, entrega: E },
    { name: "Coneta", salidas: S, entrega: E },
    { name: "Huaycama", salidas: S, entrega: E },
    { name: "La Carrera", salidas: S, entrega: E },
    { name: "La Chacarita", salidas: S, entrega: E },
    { name: "La Falda de San Antonio", salidas: S, entrega: E },
    { name: "Miraflores", salidas: S, entrega: E },
    { name: "Piedra Blanca", salidas: S, entrega: E },
    { name: "Polcos", salidas: S, entrega: E },
    { name: "Pozo del Mistol", salidas: S, entrega: E },
    { name: "San Antonio de Fray M. Esquiú", salidas: S, entrega: E },
    { name: "San Fernando del Valle de Catamarca", salidas: S, entrega: E },
    { name: "San Isidro", salidas: S, entrega: E },
    { name: "San José", salidas: S, entrega: E },
    { name: "Sumalao", salidas: S, entrega: E },
    { name: "Tres Puentes", salidas: S, entrega: E },
    { name: "Valle Viejo", salidas: S, entrega: E },
  ],
  "Chaco": [
    { name: "Barranqueras", salidas: S, entrega: E },
    { name: "Charata", salidas: S, entrega: E },
    { name: "Coronel Du Graty", salidas: S, entrega: E },
    { name: "Corzuela", salidas: S, entrega: E },
    { name: "Fontana", salidas: S, entrega: E },
    { name: "Gancedo", salidas: S, entrega: E },
    { name: "Gral. José de San Martín", salidas: S, entrega: E },
    { name: "Gral. Pinedo", salidas: S, entrega: E },
    { name: "Hermoso Campo", salidas: S, entrega: E },
    { name: "Las Breñas", salidas: S, entrega: E },
    { name: "Machagai", salidas: S, entrega: E },
    { name: "Pres. Roque Sáenz Peña", salidas: S, entrega: E },
    { name: "Puerto Tirol", salidas: S, entrega: E },
    { name: "Puerto Vilelas", salidas: S, entrega: E },
    { name: "Quitilipi", salidas: S, entrega: E },
    { name: "Resistencia", salidas: S, entrega: E },
    { name: "Santa Sylvina", salidas: S, entrega: E },
    { name: "Villa Ángela", salidas: S, entrega: E },
  ],
  "Chubut": [
    { name: "Aldea Beleiro", salidas: S, entrega: E },
    { name: "Aldea Escolar", salidas: S, entrega: E },
    { name: "Alto Río Senguer", salidas: S, entrega: E },
    { name: "Astra Km 20", salidas: S, entrega: E },
    { name: "Camarones", salidas: S, entrega: E },
    { name: "Cholila", salidas: S, entrega: E },
    { name: "Colhue Huapi", salidas: S, entrega: E },
    { name: "Comodoro Rivadavia", salidas: S, entrega: E },
    { name: "Corcovado", salidas: S, entrega: E },
    { name: "Diadema Argentina", salidas: S, entrega: E },
    { name: "Dolavon", salidas: S, entrega: E },
    { name: "El Hoyo", salidas: S, entrega: E },
    { name: "El Maitén", salidas: S, entrega: E },
    { name: "Epuyén", salidas: S, entrega: E },
    { name: "Esquel", salidas: S, entrega: E },
    { name: "Gaiman", salidas: S, entrega: E },
    { name: "Gangán", salidas: S, entrega: E },
    { name: "Garayalde", salidas: S, entrega: E },
    { name: "Gobernador Costa", salidas: S, entrega: E },
    { name: "Gualjaina", salidas: S, entrega: E },
    { name: "Herrería", salidas: S, entrega: E },
    { name: "José de San Martín", salidas: S, entrega: E },
    { name: "Lago Puelo", salidas: S, entrega: E },
    { name: "Las Chapas", salidas: S, entrega: E },
    { name: "Las Golondrinas", salidas: S, entrega: E },
    { name: "Las Plumas", salidas: S, entrega: E },
    { name: "Leleque", salidas: S, entrega: E },
    { name: "Los Altares", salidas: S, entrega: E },
    { name: "Manantiales Behr", salidas: S, entrega: E },
    { name: "Pampa del Castillo", salidas: S, entrega: E },
    { name: "Paso de los Indios", salidas: S, entrega: E },
    { name: "Paso del Sapo", salidas: S, entrega: E },
    { name: "Playa Unión", salidas: S, entrega: E },
    { name: "Puerto Madryn", salidas: S, entrega: E },
    { name: "Puerto Pirámides", salidas: S, entrega: E },
    { name: "Rada Tilly", salidas: S, entrega: E },
    { name: "Rawson", salidas: S, entrega: E },
    { name: "Río Mayo", salidas: S, entrega: E },
    { name: "Río Pico", salidas: S, entrega: E },
    { name: "Sarmiento", salidas: S, entrega: E },
    { name: "Tecka", salidas: S, entrega: E },
    { name: "Telsen", salidas: S, entrega: E },
    { name: "Trelew", salidas: S, entrega: E },
    { name: "Trevelin", salidas: S, entrega: E },
    { name: "Uzcudum", salidas: S, entrega: E },
    { name: "Veintiocho de Julio", salidas: S, entrega: E },
    { name: "Yacimiento Escalante", salidas: S, entrega: E },
  ],
  "Córdoba": [
    { name: "Achiras", salidas: S, entrega: E },
    { name: "Adelia María", salidas: S, entrega: E },
    { name: "Agua de Oro", salidas: S, entrega: E },
    { name: "Alcira Gigena", salidas: S, entrega: E },
    { name: "Alejandro", salidas: S, entrega: E },
    { name: "Almafuerte", salidas: S, entrega: E },
    { name: "Alta Gracia", salidas: S, entrega: E },
    { name: "Arias", salidas: S, entrega: E },
    { name: "Arroyo Cabral", salidas: S, entrega: E },
    { name: "Arroyo de los Patos", salidas: S, entrega: E },
    { name: "Arroyito", salidas: S, entrega: E },
    { name: "Balnearia", salidas: S, entrega: E },
    { name: "Bell Ville", salidas: S, entrega: E },
    { name: "Berrotarán", salidas: S, entrega: E },
    { name: "Canals", salidas: S, entrega: E },
    { name: "Capilla del Monte", salidas: S, entrega: E },
    { name: "Capital (Córdoba)", salidas: S, entrega: E },
    { name: "Casa Bamba", salidas: S, entrega: E },
    { name: "Colonia Caroya", salidas: S, entrega: E },
    { name: "Colonia Tirolesa", salidas: S, entrega: E },
    { name: "Coronel Moldes", salidas: S, entrega: E },
    { name: "Corral de Bustos", salidas: S, entrega: E },
    { name: "Cosquín", salidas: S, entrega: E },
    { name: "Cruz del Eje", salidas: S, entrega: E },
    { name: "Cura Brochero", salidas: S, entrega: E },
    { name: "Deán Funes", salidas: S, entrega: E },
    { name: "Falda del Carmen", salidas: S, entrega: E },
    { name: "Freyre", salidas: S, entrega: E },
    { name: "General Deheza", salidas: S, entrega: E },
    { name: "General Paz", salidas: S, entrega: E },
    { name: "Guiñazú", salidas: S, entrega: E },
    { name: "Holmberg", salidas: S, entrega: E },
    { name: "James Craik", salidas: S, entrega: E },
    { name: "Jesús María", salidas: S, entrega: E },
    { name: "Jovita", salidas: S, entrega: E },
    { name: "Juárez Celman", salidas: S, entrega: E },
    { name: "Justiniano Posse", salidas: S, entrega: E },
    { name: "La Calera", salidas: S, entrega: E },
    { name: "La Carlota", salidas: S, entrega: E },
    { name: "La Cumbre", salidas: S, entrega: E },
    { name: "La Falda", salidas: S, entrega: E },
    { name: "La Para", salidas: S, entrega: E },
    { name: "La Playosa", salidas: S, entrega: E },
    { name: "La Población", salidas: S, entrega: E },
    { name: "La Puerta", salidas: S, entrega: E },
    { name: "Laborde", salidas: S, entrega: E },
    { name: "Laboulaye", salidas: S, entrega: E },
    { name: "Laguna Larga", salidas: S, entrega: E },
    { name: "Las Acequias", salidas: S, entrega: E },
    { name: "Las Higueras", salidas: S, entrega: E },
    { name: "Las Perdices", salidas: S, entrega: E },
    { name: "Las Rabonas", salidas: S, entrega: E },
    { name: "Las Tapias", salidas: S, entrega: E },
    { name: "Las Varillas", salidas: S, entrega: E },
    { name: "Leones", salidas: S, entrega: E },
    { name: "Los Hornillos", salidas: S, entrega: E },
    { name: "Los Pozos", salidas: S, entrega: E },
    { name: "Luque", salidas: S, entrega: E },
    { name: "Malagueño", salidas: S, entrega: E },
    { name: "Malvinas Argentinas", salidas: S, entrega: E },
    { name: "Marcos Juárez", salidas: S, entrega: E },
    { name: "Marull", salidas: S, entrega: E },
    { name: "Mendiolaza", salidas: S, entrega: E },
    { name: "Miramar", salidas: S, entrega: E },
    { name: "Monte Buey", salidas: S, entrega: E },
    { name: "Monte Maíz", salidas: S, entrega: E },
    { name: "Montecristo", salidas: S, entrega: E },
    { name: "Morrison", salidas: S, entrega: E },
    { name: "Morteros", salidas: S, entrega: E },
    { name: "Nono", salidas: S, entrega: E },
    { name: "Oliva", salidas: S, entrega: E },
    { name: "Oncativo", salidas: S, entrega: E },
    { name: "Pajas Blancas", salidas: S, entrega: E },
    { name: "Pascanas", salidas: S, entrega: E },
    { name: "Pilar", salidas: S, entrega: E },
    { name: "Piquillín", salidas: S, entrega: E },
    { name: "Porteña", salidas: S, entrega: E },
    { name: "Quilino", salidas: S, entrega: E },
    { name: "Rafael García", salidas: S, entrega: E },
    { name: "Río Ceballos", salidas: S, entrega: E },
    { name: "Río Cuarto", salidas: S, entrega: E },
    { name: "Río Primero", salidas: S, entrega: E },
    { name: "Río Segundo", salidas: S, entrega: E },
    { name: "Río Tercero", salidas: S, entrega: E },
    { name: "Saldán", salidas: S, entrega: E },
    { name: "Salsipuedes", salidas: S, entrega: E },
    { name: "Sampacho", salidas: S, entrega: E },
    { name: "San Francisco", salidas: S, entrega: E },
    { name: "San Humberto", salidas: S, entrega: E },
    { name: "San Javier", salidas: S, entrega: E },
    { name: "Santa Ana", salidas: S, entrega: E },
    { name: "Santa Catalina", salidas: S, entrega: E },
    { name: "Santa Rosa de Río Primero", salidas: S, entrega: E },
    { name: "Ticino", salidas: S, entrega: E },
    { name: "Tío Pujio", salidas: S, entrega: E },
    { name: "Toledo", salidas: S, entrega: E },
    { name: "Tránsito", salidas: S, entrega: E },
    { name: "Unquillo", salidas: S, entrega: E },
    { name: "Vicuña Mackenna", salidas: S, entrega: E },
    { name: "Villa Allende", salidas: S, entrega: E },
    { name: "Villa Carlos Paz", salidas: S, entrega: E },
    { name: "Villa de Soto", salidas: S, entrega: E },
    { name: "Villa del Rosario", salidas: S, entrega: E },
    { name: "Villa Dolores", salidas: S, entrega: E },
    { name: "Villa General Belgrano", salidas: S, entrega: E },
    { name: "Villa María", salidas: S, entrega: E },
    { name: "Villa Nueva", salidas: S, entrega: E },
    { name: "Villas de las Rosas", salidas: S, entrega: E },
    { name: "Yacanto", salidas: S, entrega: E },
    { name: "Yocsina", salidas: S, entrega: E },
  ],
  "Corrientes": [
    { name: "Colonia Carolina", salidas: S, entrega: E },
    { name: "Corrientes", salidas: S, entrega: E },
    { name: "Goya", salidas: S, entrega: E },
    { name: "Lavalle", salidas: S, entrega: E },
    { name: "Santa Lucía", salidas: S, entrega: E },
    { name: "Paso de los Libres", salidas: S, entrega: E },
  ],
  "Entre Ríos": [
    { name: "Aldea Protestante", salidas: S, entrega: E },
    { name: "Aldea Valle María", salidas: S, entrega: E },
    { name: "Aranguren", salidas: S, entrega: E },
    { name: "Camps", salidas: S, entrega: E },
    { name: "Colón", salidas: S, entrega: E },
    { name: "Concepción del Uruguay", salidas: S, entrega: E },
    { name: "Concordia", salidas: S, entrega: E },
    { name: "Crespo", salidas: S, entrega: E },
    { name: "Diamante", salidas: S, entrega: E },
    { name: "General Ramírez", salidas: S, entrega: E },
    { name: "Gualeguaychú", salidas: S, entrega: E },
    { name: "Hernández", salidas: S, entrega: E },
    { name: "Paraná", salidas: S, entrega: E },
    { name: "San José", salidas: S, entrega: E },
    { name: "Villa Elisa", salidas: S, entrega: E },
    { name: "Villa Gral. San Martín", salidas: S, entrega: E },
  ],
  "Formosa": [
    { name: "Clorinda", salidas: S, entrega: E },
    { name: "Espinillo", salidas: S, entrega: E },
    { name: "Formosa", salidas: S, entrega: E },
    { name: "General Belgrano", salidas: S, entrega: E },
    { name: "Laguna Blanca", salidas: S, entrega: E },
    { name: "Laguna Naick Neck", salidas: S, entrega: E },
  ],
  "Jujuy": [
    { name: "Abra Pampa", salidas: S, entrega: E },
    { name: "Barrio Negro", salidas: S, entrega: E },
    { name: "El Carmen", salidas: S, entrega: E },
    { name: "El Ceibal", salidas: S, entrega: E },
    { name: "El Triangulito", salidas: S, entrega: E },
    { name: "Huacalera", salidas: S, entrega: E },
    { name: "Ing. La Esperanza", salidas: S, entrega: E },
    { name: "La Intermedia", salidas: S, entrega: E },
    { name: "La Mendieta", salidas: S, entrega: E },
    { name: "León", salidas: S, entrega: E },
    { name: "Lozano", salidas: S, entrega: E },
    { name: "Los Alisos", salidas: S, entrega: E },
    { name: "Los Ávalos", salidas: S, entrega: E },
    { name: "Monterrico", salidas: S, entrega: E },
    { name: "Pampa Blanca", salidas: S, entrega: E },
    { name: "Pampitas", salidas: S, entrega: E },
    { name: "Palpalá", salidas: S, entrega: E },
    { name: "Puesto del Márquez", salidas: S, entrega: E },
    { name: "Perico", salidas: S, entrega: E },
    { name: "Pumahuasi", salidas: S, entrega: E },
    { name: "Purmamarca", salidas: S, entrega: E },
    { name: "Río Blanco", salidas: S, entrega: E },
    { name: "San Pedro de Jujuy", salidas: S, entrega: E },
    { name: "San Salvador de Jujuy", salidas: S, entrega: E },
    { name: "San Juancito", salidas: S, entrega: E },
    { name: "Santa Bárbara", salidas: S, entrega: E },
    { name: "Santo Domingo", salidas: S, entrega: E },
    { name: "San Pablo de Reyes", salidas: S, entrega: E },
    { name: "Tres Cruces", salidas: S, entrega: E },
    { name: "Villa Jardín de Reyes", salidas: S, entrega: E },
    { name: "Yala", salidas: S, entrega: E },
  ],
  "La Pampa": [
    { name: "Alta Italia", salidas: S, entrega: E },
    { name: "Arata", salidas: S, entrega: E },
    { name: "Larroude", salidas: S, entrega: E },
    { name: "Caleufú", salidas: S, entrega: E },
    { name: "Catriló", salidas: S, entrega: E },
    { name: "Colonia Barón", salidas: S, entrega: E },
    { name: "Embajador Martini", salidas: S, entrega: E },
    { name: "Eduardo Castex", salidas: S, entrega: E },
    { name: "General Pico", salidas: S, entrega: E },
    { name: "Hilario Lagos", salidas: S, entrega: E },
    { name: "Ingeniero Luiggi", salidas: S, entrega: E },
    { name: "Intendente Alvear", salidas: S, entrega: E },
    { name: "Lonquimay", salidas: S, entrega: E },
    { name: "Macachín", salidas: S, entrega: E },
    { name: "Parera", salidas: S, entrega: E },
    { name: "Quemú Quemú", salidas: S, entrega: E },
    { name: "Rancul", salidas: S, entrega: E },
    { name: "Realicó", salidas: S, entrega: E },
    { name: "Santa Rosa de La Pampa", salidas: S, entrega: E },
    { name: "Trenel", salidas: S, entrega: E },
    { name: "Victorica", salidas: S, entrega: E },
    { name: "Vértiz", salidas: S, entrega: E },
    { name: "Villa Mirasol", salidas: S, entrega: E },
  ],
  "La Rioja": [
    { name: "Chamical", salidas: "Salidas diarias", entrega: "Hasta 48hs hábiles" },
    { name: "Chilecito", salidas: "Salidas diarias", entrega: "Hasta 48hs hábiles" },
    { name: "Famatina", salidas: "Salidas diarias", entrega: "Hasta 48hs hábiles" },
    { name: "La Rioja", salidas: "Salidas diarias", entrega: "Hasta 48hs hábiles" },
    { name: "Nonogasta", salidas: "Salidas diarias", entrega: "Hasta 48hs hábiles" },
    { name: "Vichigasta", salidas: "Salidas diarias", entrega: "Hasta 48hs hábiles" },
  ],
  "Mendoza": [
    { name: "Fray Luis Beltrán", salidas: S, entrega: E },
    { name: "General Gutiérrez", salidas: S, entrega: E },
    { name: "Godoy Cruz", salidas: S, entrega: E },
    { name: "Guaymallén", salidas: S, entrega: E },
    { name: "Las Heras", salidas: S, entrega: E },
    { name: "Luján de Cuyo", salidas: S, entrega: E },
    { name: "Maipú", salidas: S, entrega: E },
    { name: "Mendoza", salidas: S, entrega: E },
    { name: "Palmira", salidas: S, entrega: E },
    { name: "Perdriel", salidas: S, entrega: E },
    { name: "Rodeo de la Cruz", salidas: S, entrega: E },
    { name: "Rodeo del Medio", salidas: S, entrega: E },
    { name: "San Francisco del Monte", salidas: S, entrega: E },
    { name: "San Rafael", salidas: S, entrega: E },
    { name: "Tunuyán", salidas: S, entrega: E },
  ],
  "Misiones": [
    { name: "Posadas", salidas: S, entrega: E },
  ],
  "Neuquén": [
    { name: "Agua del Cajón", salidas: S, entrega: E },
    { name: "Aguada Pichana", salidas: S, entrega: E },
    { name: "Al Norte Dorsal", salidas: S, entrega: E },
    { name: "Alicurá", salidas: S, entrega: E },
    { name: "Aluminé", salidas: S, entrega: E },
    { name: "Andacollo", salidas: S, entrega: E },
    { name: "Añelo", salidas: S, entrega: E },
    { name: "Arroyito", salidas: S, entrega: E },
    { name: "Balsa Las Perlas", salidas: S, entrega: E },
    { name: "Buta Ranquil", salidas: S, entrega: E },
    { name: "Campo Grande", salidas: S, entrega: E },
    { name: "Caviahue", salidas: S, entrega: E },
    { name: "Centenario", salidas: S, entrega: E },
    { name: "Chos Malal", salidas: S, entrega: E },
    { name: "Cinco Saltos", salidas: S, entrega: E },
    { name: "Cipolletti", salidas: S, entrega: E },
    { name: "Copahue", salidas: S, entrega: E },
    { name: "Covunco", salidas: S, entrega: E },
    { name: "Cutral Co", salidas: S, entrega: E },
    { name: "Desfiladero C. Bayo", salidas: S, entrega: E },
    { name: "El Cholar", salidas: S, entrega: E },
    { name: "El Huecú", salidas: S, entrega: E },
    { name: "El Trapial", salidas: S, entrega: E },
    { name: "Fortín de Piedra", salidas: S, entrega: E },
    { name: "Huingán Co", salidas: S, entrega: E },
    { name: "Junín de los Andes", salidas: S, entrega: E },
    { name: "Lago Hermoso", salidas: S, entrega: E },
    { name: "Lago Huá Hum", salidas: S, entrega: E },
    { name: "Lago Lolog", salidas: S, entrega: E },
    { name: "Las Lajas", salidas: S, entrega: E },
    { name: "Las Ovejas", salidas: S, entrega: E },
    { name: "Loma de la Lata", salidas: S, entrega: E },
    { name: "Loma de la Yegua", salidas: S, entrega: E },
    { name: "Loncopué", salidas: S, entrega: E },
    { name: "Mariano Moreno", salidas: S, entrega: E },
    { name: "Meliquina", salidas: S, entrega: E },
    { name: "Neuquén", salidas: S, entrega: E },
    { name: "Picún Leufú", salidas: S, entrega: E },
    { name: "Piedra del Águila", salidas: S, entrega: E },
    { name: "Plaza Huincul", salidas: S, entrega: E },
    { name: "Plottier", salidas: S, entrega: E },
    { name: "Puesto Hernández", salidas: S, entrega: E },
    { name: "Quila Quina", salidas: S, entrega: E },
    { name: "Rincón de los Sauces", salidas: S, entrega: E },
    { name: "San Martín de los Andes", salidas: S, entrega: E },
    { name: "San Patricio C.", salidas: S, entrega: E },
    { name: "Senillosa", salidas: S, entrega: E },
    { name: "Sierra Chata", salidas: S, entrega: E },
    { name: "Taquimilán", salidas: S, entrega: E },
    { name: "Villa El Chocón", salidas: S, entrega: E },
    { name: "Villa La Angostura", salidas: S, entrega: E },
    { name: "Villa Manzano", salidas: S, entrega: E },
    { name: "Villa Pehuenia", salidas: S, entrega: E },
    { name: "Villa Traful", salidas: S, entrega: E },
    { name: "Vista Alegre", salidas: S, entrega: E },
    { name: "Vista Alegre Norte", salidas: S, entrega: E },
    { name: "Vista Alegre Sur", salidas: S, entrega: E },
    { name: "Yac. Al Norte de la Dorsal", salidas: S, entrega: E },
    { name: "Yac. Al Sur de la Dorsal", salidas: S, entrega: E },
    { name: "Yac. Cañadón Amarillo", salidas: S, entrega: E },
    { name: "Yac. Catriel Oeste", salidas: S, entrega: E },
    { name: "Yac. Centro Oeste", salidas: S, entrega: E },
    { name: "Yac. Chihuidos / Sierra Negra", salidas: S, entrega: E },
    { name: "Yac. Huantraico", salidas: S, entrega: E },
    { name: "Yac. Lindero Atravesado", salidas: S, entrega: E },
    { name: "Yac. Lomitas", salidas: S, entrega: E },
    { name: "Yac. Los Bastos", salidas: S, entrega: E },
    { name: "Yac. San Roque", salidas: S, entrega: E },
    { name: "Yac. Sierra Negra", salidas: S, entrega: E },
    { name: "Yac. Toledo", salidas: S, entrega: E },
    { name: "Yacimiento Challaco", salidas: S, entrega: E },
    { name: "Yacimiento Confluencia", salidas: S, entrega: E },
    { name: "Yacimiento El Mangrullo", salidas: S, entrega: E },
    { name: "Yacimiento El Orejano", salidas: S, entrega: E },
    { name: "Yacimiento El Portón", salidas: S, entrega: E },
    { name: "Yacimiento El Porvenir", salidas: S, entrega: E },
    { name: "Yacimiento Sierra Barrosa", salidas: S, entrega: E },
    { name: "Zapala", salidas: S, entrega: E },
  ],
  "Río Negro": [
    { name: "Allen", salidas: S, entrega: E },
    { name: "Barda del Medio", salidas: S, entrega: E },
    { name: "Bariloche Zona Urbana", salidas: S, entrega: E },
    { name: "Cervantes", salidas: S, entrega: E },
    { name: "Chelforo", salidas: S, entrega: E },
    { name: "Chichinales", salidas: S, entrega: E },
    { name: "Chimpay", salidas: S, entrega: E },
    { name: "Choele Choel", salidas: S, entrega: E },
    { name: "Cnel. J. J. Gómez", salidas: S, entrega: E },
    { name: "Colonia Catriel", salidas: S, entrega: E },
    { name: "Contralmirante Cordero", salidas: S, entrega: E },
    { name: "Coronel Belisle", salidas: S, entrega: E },
    { name: "Cte. M. Guerrico", salidas: S, entrega: E },
    { name: "Darwin", salidas: S, entrega: E },
    { name: "Dina Huapi", salidas: S, entrega: E },
    { name: "El Bolsón", salidas: S, entrega: E },
    { name: "Entre Lomas", salidas: S, entrega: E },
    { name: "F. Luis Beltrán", salidas: S, entrega: E },
    { name: "Gastre", salidas: S, entrega: E },
    { name: "General Conesa", salidas: S, entrega: E },
    { name: "General Enrique Godoy", salidas: S, entrega: E },
    { name: "General Fernández Oro", salidas: S, entrega: E },
    { name: "General Roca", salidas: S, entrega: E },
    { name: "Ingeniero Jacobacci", salidas: S, entrega: E },
    { name: "Ingeniero L. Huergo", salidas: S, entrega: E },
    { name: "La Adela", salidas: S, entrega: E },
    { name: "Lamarque", salidas: S, entrega: E },
    { name: "Las Grutas", salidas: S, entrega: E },
    { name: "Las Jarillas", salidas: S, entrega: E },
    { name: "Los Menucos", salidas: S, entrega: E },
    { name: "Mainque", salidas: S, entrega: E },
    { name: "Maquinchao", salidas: S, entrega: E },
    { name: "Ñorquinco", salidas: S, entrega: E },
    { name: "Onelli", salidas: S, entrega: E },
    { name: "Ovando", salidas: S, entrega: E },
    { name: "Padre A. Stefanelli", salidas: S, entrega: E },
    { name: "Playas Doradas", salidas: S, entrega: E },
    { name: "Pomona", salidas: S, entrega: E },
    { name: "Río Chico", salidas: S, entrega: E },
    { name: "Río Colorado", salidas: S, entrega: E },
    { name: "San Antonio Oeste", salidas: S, entrega: E },
    { name: "Sargento Vidal", salidas: S, entrega: E },
    { name: "Sierra Colorada", salidas: S, entrega: E },
    { name: "Sierra Grande", salidas: S, entrega: E },
    { name: "Valcheta", salidas: S, entrega: E },
    { name: "Viedma", salidas: S, entrega: E },
    { name: "Villa Regina", salidas: S, entrega: E },
    { name: "Yac. Estancia Vieja", salidas: S, entrega: E },
    { name: "Yac. Oldelval", salidas: S, entrega: E },
    { name: "Yacimiento Medanito", salidas: S, entrega: E },
  ],
  "Salta": [
    { name: "Aguaray", salidas: S, entrega: E },
    { name: "Apolinario Saravia", salidas: S, entrega: E },
    { name: "Bella Vista", salidas: S, entrega: E },
    { name: "Campo Quijano", salidas: S, entrega: E },
    { name: "Castañares", salidas: S, entrega: E },
    { name: "Cerrillos", salidas: S, entrega: E },
    { name: "Chicoana", salidas: S, entrega: E },
    { name: "Coronel Moldes", salidas: S, entrega: E },
    { name: "Cobos", salidas: S, entrega: E },
    { name: "El Carril", salidas: S, entrega: E },
    { name: "El Mollal", salidas: S, entrega: E },
    { name: "El Pucará", salidas: S, entrega: E },
    { name: "El Encón", salidas: S, entrega: E },
    { name: "Embarcación", salidas: S, entrega: E },
    { name: "Gral. Güemes", salidas: S, entrega: E },
    { name: "Gral. Mosconi", salidas: S, entrega: E },
    { name: "Gral. Pizarro", salidas: S, entrega: E },
    { name: "Hipólito Yrigoyen", salidas: S, entrega: E },
    { name: "La Isla", salidas: S, entrega: E },
    { name: "La Merced", salidas: S, entrega: E },
    { name: "Las Lajitas", salidas: S, entrega: E },
    { name: "La Silleta", salidas: S, entrega: E },
    { name: "Luis Burela", salidas: S, entrega: E },
    { name: "Lumbreras", salidas: S, entrega: E },
    { name: "Metán", salidas: S, entrega: E },
    { name: "Orán", salidas: S, entrega: E },
    { name: "Pichanal", salidas: S, entrega: E },
    { name: "Piquirenda", salidas: S, entrega: E },
    { name: "Pizarro", salidas: S, entrega: E },
    { name: "Quebrachal", salidas: S, entrega: E },
    { name: "Rosario de Lerma", salidas: S, entrega: E },
    { name: "Rosario de la Frontera", salidas: S, entrega: E },
    { name: "Rinconada", salidas: S, entrega: E },
    { name: "Salta", salidas: S, entrega: E },
    { name: "Salvador Mazza", salidas: S, entrega: E },
    { name: "San Agustín", salidas: S, entrega: E },
    { name: "San Lorenzo", salidas: S, entrega: E },
    { name: "Tartagal", salidas: S, entrega: E },
    { name: "Tobatirenda", salidas: S, entrega: E },
    { name: "Vaqueros", salidas: S, entrega: E },
    { name: "Yacuy", salidas: S, entrega: E },
  ],
  "San Juan": [
    { name: "San Juan", salidas: S, entrega: E },
    { name: "Pocito", salidas: S, entrega: E },
    { name: "Santa Lucía", salidas: S, entrega: E },
  ],
  "San Luis": [
    { name: "Merlo", salidas: S, entrega: E },
    { name: "San Luis", salidas: S, entrega: E },
  ],
  "Santa Cruz": [
    { name: "Caleta Olivia", salidas: S, entrega: E },
    { name: "Cañadón Seco", salidas: S, entrega: E },
    { name: "Cerro Vanguardia", salidas: S, entrega: E },
    { name: "Comandante Luis Piedra Buena", salidas: S, entrega: E },
    { name: "El Calafate", salidas: S, entrega: E },
    { name: "El Chaltén", salidas: S, entrega: E },
    { name: "El Guadal", salidas: S, entrega: E },
    { name: "El Huemul", salidas: S, entrega: E },
    { name: "Gobernador Gregores", salidas: S, entrega: E },
    { name: "Julia Dufour", salidas: S, entrega: E },
    { name: "Koluel Kayke", salidas: S, entrega: E },
    { name: "La Dorotea", salidas: S, entrega: E },
    { name: "Las Heras", salidas: S, entrega: E },
    { name: "Los Antiguos", salidas: S, entrega: E },
    { name: "Los Perales", salidas: S, entrega: E },
    { name: "Paraje 3 Cerros Est. de Servicios", salidas: S, entrega: E },
    { name: "Perito Moreno", salidas: S, entrega: E },
    { name: "Pico Truncado", salidas: S, entrega: E },
    { name: "Piedra Clavada", salidas: S, entrega: E },
    { name: "Planta Compresora Bosque Petrificado", salidas: S, entrega: E },
    { name: "Planta Compresora La Silvita", salidas: S, entrega: E },
    { name: "Planta Compresora Monte León", salidas: S, entrega: E },
    { name: "Planta Compresora Río Seco", salidas: S, entrega: E },
    { name: "Puerto Deseado", salidas: S, entrega: E },
    { name: "Puerto San Julián", salidas: S, entrega: E },
    { name: "Puerto Santa Cruz", salidas: S, entrega: E },
    { name: "Punta Bandera", salidas: S, entrega: E },
    { name: "Punta Quilla", salidas: S, entrega: E },
    { name: "Río Gallegos", salidas: S, entrega: E },
    { name: "Río Turbio", salidas: S, entrega: E },
    { name: "Rospentek", salidas: S, entrega: E },
    { name: "Veintiocho de Noviembre", salidas: S, entrega: E },
    { name: "Yac. Barda Las Vegas", salidas: S, entrega: E },
    { name: "Yac. Boleadoras", salidas: S, entrega: E },
    { name: "Yac. Cabo Vírgenes", salidas: S, entrega: E },
    { name: "Yac. La Maggie", salidas: S, entrega: E },
    { name: "Yac. María Inés", salidas: S, entrega: E },
    { name: "Yac. Punta Loyola", salidas: S, entrega: E },
    { name: "Yac. Salto", salidas: S, entrega: E },
  ],
  "Santa Fe": [
    { name: "Alvear", salidas: S, entrega: E },
    { name: "Arequito", salidas: S, entrega: E },
    { name: "Armstrong", salidas: S, entrega: E },
    { name: "Arroyo Seco", salidas: S, entrega: E },
    { name: "Arteaga", salidas: S, entrega: E },
    { name: "Avellaneda", salidas: S, entrega: E },
    { name: "Calchaquí", salidas: S, entrega: E },
    { name: "Cañada de Gómez", salidas: S, entrega: E },
    { name: "Capitán Bermúdez", salidas: S, entrega: E },
    { name: "Carcarañá", salidas: S, entrega: E },
    { name: "Carlos Pellegrini", salidas: S, entrega: E },
    { name: "Casilda", salidas: S, entrega: E },
    { name: "Ceres", salidas: S, entrega: E },
    { name: "Chabás", salidas: S, entrega: E },
    { name: "El Trébol", salidas: S, entrega: E },
    { name: "Empalme", salidas: S, entrega: E },
    { name: "Esperanza", salidas: S, entrega: E },
    { name: "Fighiera", salidas: S, entrega: E },
    { name: "Firmat", salidas: S, entrega: E },
    { name: "Franck", salidas: S, entrega: E },
    { name: "Fray Luis Beltrán", salidas: S, entrega: E },
    { name: "Frontera", salidas: S, entrega: E },
    { name: "Funes", salidas: S, entrega: E },
    { name: "Gálvez", salidas: S, entrega: E },
    { name: "General Lagos", salidas: S, entrega: E },
    { name: "Gessler", salidas: S, entrega: E },
    { name: "Gobernador Crespo", salidas: S, entrega: E },
    { name: "Gobernador Baigorria", salidas: S, entrega: E },
    { name: "Guadalupe Norte", salidas: S, entrega: E },
    { name: "Ibarlucea", salidas: S, entrega: E },
    { name: "La Criolla", salidas: S, entrega: E },
    { name: "Las Parejas", salidas: S, entrega: E },
    { name: "Las Rosas", salidas: S, entrega: E },
    { name: "Las Toscas", salidas: S, entrega: E },
    { name: "Las Tunas", salidas: S, entrega: E },
    { name: "Los Molinos", salidas: S, entrega: E },
    { name: "Margarita", salidas: S, entrega: E },
    { name: "María Juana", salidas: S, entrega: E },
    { name: "María Susana", salidas: S, entrega: E },
    { name: "Parque Industrial Pérez", salidas: S, entrega: E },
    { name: "Pavón", salidas: S, entrega: E },
    { name: "Piamonte", salidas: S, entrega: E },
    { name: "Pueblo Esther", salidas: S, entrega: E },
    { name: "Puerto Gral. San Martín", salidas: S, entrega: E },
    { name: "Rafaela", salidas: S, entrega: E },
    { name: "Reconquista", salidas: S, entrega: E },
    { name: "Ricardone", salidas: S, entrega: E },
    { name: "Roldán", salidas: S, entrega: E },
    { name: "Rosario", salidas: S, entrega: E },
    { name: "San Agustín", salidas: S, entrega: E },
    { name: "San Antonio de Obligado", salidas: S, entrega: E },
    { name: "San Carlos", salidas: S, entrega: E },
    { name: "Sanford", salidas: S, entrega: E },
    { name: "San Javier", salidas: S, entrega: E },
    { name: "San Jerónimo del Sauce", salidas: S, entrega: E },
    { name: "San Jerónimo", salidas: S, entrega: E },
    { name: "San José de la Esquina", salidas: S, entrega: E },
    { name: "San Jorge", salidas: S, entrega: E },
    { name: "San Justo", salidas: S, entrega: E },
    { name: "San Lorenzo", salidas: S, entrega: E },
    { name: "Santa Fe Capital", salidas: S, entrega: E },
    { name: "Santo Tomé", salidas: S, entrega: E },
    { name: "Sauce Viejo", salidas: S, entrega: E },
    { name: "Soldini", salidas: S, entrega: E },
    { name: "Sunchales", salidas: S, entrega: E },
    { name: "Tacuarendí", salidas: S, entrega: E },
    { name: "Tostado", salidas: S, entrega: E },
    { name: "Venado Tuerto", salidas: S, entrega: E },
    { name: "Vera", salidas: S, entrega: E },
    { name: "Vera y Pintado", salidas: S, entrega: E },
    { name: "Villa Constitución", salidas: S, entrega: E },
    { name: "Villada", salidas: S, entrega: E },
    { name: "Villa Gobernador Gálvez", salidas: S, entrega: E },
    { name: "Villa Ocampo", salidas: S, entrega: E },
  ],
  "Santiago del Estero": [
    { name: "Añatuya", salidas: S, entrega: E },
    { name: "Arraga", salidas: S, entrega: E },
    { name: "Beltrán", salidas: S, entrega: E },
    { name: "Cardozos", salidas: S, entrega: E },
    { name: "Choya", salidas: S, entrega: E },
    { name: "Clodomira", salidas: S, entrega: E },
    { name: "Colonia Dora", salidas: S, entrega: E },
    { name: "Fernández", salidas: S, entrega: E },
    { name: "Forres", salidas: S, entrega: E },
    { name: "Frías", salidas: S, entrega: E },
    { name: "Garza", salidas: S, entrega: E },
    { name: "Icaño", salidas: S, entrega: E },
    { name: "Laprida", salidas: S, entrega: E },
    { name: "Lavalle", salidas: S, entrega: E },
    { name: "Loreto", salidas: S, entrega: E },
    { name: "Los Arias", salidas: S, entrega: E },
    { name: "Los Quiroga", salidas: S, entrega: E },
    { name: "Lugones", salidas: S, entrega: E },
    { name: "Nasalo", salidas: S, entrega: E },
    { name: "Nueva Francia", salidas: S, entrega: E },
    { name: "Pozo de Loma", salidas: S, entrega: E },
    { name: "Punco", salidas: S, entrega: E },
    { name: "Quimilí", salidas: S, entrega: E },
    { name: "Robles", salidas: S, entrega: E },
    { name: "San Pedro", salidas: S, entrega: E },
    { name: "San Vicente", salidas: S, entrega: E },
    { name: "Santiago del Estero", salidas: S, entrega: E },
    { name: "Sauce Bajada", salidas: S, entrega: E },
    { name: "Símbol", salidas: S, entrega: E },
    { name: "Simbólar", salidas: S, entrega: E },
    { name: "Suncho", salidas: S, entrega: E },
    { name: "Tapso", salidas: S, entrega: E },
    { name: "Termas", salidas: S, entrega: E },
    { name: "Vilelas", salidas: S, entrega: E },
    { name: "Vilmer", salidas: S, entrega: E },
    { name: "Vuelta de Bajo", salidas: S, entrega: E },
    { name: "Yuchán", salidas: S, entrega: E },
  ],
  "Tierra del Fuego": [
    { name: "Cañadón Alfa", salidas: S, entrega: E },
    { name: "Río Grande", salidas: S, entrega: E },
    { name: "San Sebastián", salidas: S, entrega: E },
    { name: "Tolhuin", salidas: S, entrega: E },
    { name: "Ushuaia", salidas: S, entrega: E },
    { name: "Yac. Río Cullen", salidas: S, entrega: E },
  ],
  "Tucumán": [
    { name: "Acheral", salidas: S, entrega: E },
    { name: "Aguilares", salidas: S, entrega: E },
    { name: "Alberdi", salidas: S, entrega: E },
    { name: "Alderetes", salidas: S, entrega: E },
    { name: "Alto Verde", salidas: S, entrega: E },
    { name: "Arcadia", salidas: S, entrega: E },
    { name: "Banda del Río Salí", salidas: S, entrega: E },
    { name: "Bella Vista", salidas: S, entrega: E },
    { name: "Cevil Redondo", salidas: S, entrega: E },
    { name: "Chañaritos", salidas: S, entrega: E },
    { name: "Chicligasta", salidas: S, entrega: E },
    { name: "Concepción", salidas: S, entrega: E },
    { name: "Cruz Alta", salidas: S, entrega: E },
    { name: "El Cadillal", salidas: S, entrega: E },
    { name: "El Colmenar", salidas: S, entrega: E },
    { name: "Famaillá", salidas: S, entrega: E },
    { name: "La Cocha", salidas: S, entrega: E },
    { name: "Lastenia", salidas: S, entrega: E },
    { name: "Lules", salidas: S, entrega: E },
    { name: "Manantial", salidas: S, entrega: E },
    { name: "Manuel Fernández", salidas: S, entrega: E },
    { name: "Monteros", salidas: S, entrega: E },
    { name: "Piedritas", salidas: S, entrega: E },
    { name: "Ranchillos", salidas: S, entrega: E },
    { name: "Río Colorado", salidas: S, entrega: E },
    { name: "Reducción", salidas: S, entrega: E },
    { name: "Río Chico", salidas: S, entrega: E },
    { name: "Río Seco", salidas: S, entrega: E },
    { name: "San Miguel de Tucumán", salidas: S, entrega: E },
    { name: "San Pablo", salidas: S, entrega: E },
    { name: "Simoca", salidas: S, entrega: E },
    { name: "Tafí Viejo", salidas: S, entrega: E },
    { name: "Talitas", salidas: S, entrega: E },
    { name: "Villa Carmela", salidas: S, entrega: E },
    { name: "Villa Belgrano", salidas: S, entrega: E },
    { name: "Villa Quinteros", salidas: S, entrega: E },
    { name: "Yerba Buena", salidas: S, entrega: E },
  ],
};
